name: release-to-test
on:
  push:
    branches:
      - "master"      
  workflow_dispatch:

jobs:
  ubuntu-16_04:
    name: ubuntu-16_04
    runs-on: ubuntu-16.04
    steps:
      - name: Release to test
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
        run: heroku container:release web --app blank-fplbot-test
